import { StyleSheet } from 'react-native';

const EquipmentDetailStyle = StyleSheet.create({
  safe: { flex: 1 },
  imageContainer: { height: 280, position: 'relative' },
  image: { width: '100%', height: '100%' },
  imageOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 100,
    paddingTop: 16,
    paddingHorizontal: 16,
  },
  backBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  favBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 16,
    top: 16,
  },
  availBadge: {
    position: 'absolute',
    bottom: 16,
    right: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  availText: { color: '#FFFFFF', fontSize: 12, fontWeight: '700' },
  body: {
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: -20,
    padding: 24,
    gap: 12,
    paddingBottom: 120,
  },
  topRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  categoryTag: {
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 8,
  },
  categoryText: { fontSize: 12, fontWeight: '700' },
  conditionRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  conditionText: { fontSize: 12 },
  name: { fontSize: 22, fontWeight: '800', lineHeight: 28 },
  description: { fontSize: 14, lineHeight: 22 },
  sectionTitle: { fontSize: 16, fontWeight: '700', marginTop: 8 },
  ratesRow: { flexDirection: 'row', gap: 10 },
  rateCard: {
    flex: 1,
    padding: 14,
    borderRadius: 12,
    alignItems: 'center',
    gap: 4,
    borderWidth: 1,
  },
  rateLabel: { fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5 },
  rateValue: { fontSize: 15, fontWeight: '800' },
  specsCard: {
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
  },
  specRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 12,
  },
  specKey: { fontSize: 13 },
  specVal: { fontSize: 13, fontWeight: '600', maxWidth: '55%', textAlign: 'right' },
  cta: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 32,
    borderTopWidth: 1,
  },
  ctaFrom: { fontSize: 11, textTransform: 'uppercase', letterSpacing: 0.5 },
  ctaRate: { fontSize: 22, fontWeight: '800' },
  rentBtn: {
    paddingHorizontal: 32,
    paddingVertical: 14,
    borderRadius: 14,
  },
  rentBtnText: { fontSize: 16, fontWeight: '700' },
});

export default EquipmentDetailStyle;
