import { StyleSheet } from 'react-native';

const RentalRequestsStyle = StyleSheet.create({
  safe: { flex: 1 },
  header: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 12, borderBottomWidth: 1, gap: 4 },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  title: { fontSize: 22, fontWeight: '800' },
  badge: { width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  badgeText: { color: '#FFF', fontSize: 11, fontWeight: '800' },
  subtitle: { fontSize: 13 },
  filterBar: { flexGrow: 0, borderBottomWidth: 1 },
  filterScroll: { paddingHorizontal: 16, paddingVertical: 12, gap: 8 },
  filterChip: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1.5,
    marginRight: 4,
    minWidth: 52,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterText: { fontSize: 12, fontWeight: '700', textAlign: 'center' },
  list: { padding: 16, paddingBottom: 32 },
  card: {
    borderRadius: 14, marginBottom: 12, borderWidth: 1.5,
    overflow: 'hidden', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.07, shadowRadius: 6, elevation: 2,
  },
  cardTop: { flexDirection: 'row', padding: 14, gap: 10 },
  cardInfo: { flex: 1, gap: 4 },
  equipName: { fontSize: 14, fontWeight: '700' },
  customerName: { fontSize: 12 },
  dates: { fontSize: 12 },
  cardRight: { alignItems: 'flex-end', gap: 6 },
  cost: { fontSize: 14, fontWeight: '700' },
  quickActions: { flexDirection: 'row', borderTopWidth: 1, gap: 1 },
  quickBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5, paddingVertical: 10 },
  quickBtnText: { fontSize: 13, fontWeight: '700' },
  modalOverlay: { flex: 1, justifyContent: 'flex-end' },
  modalCard: { borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '90%' },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1 },
  modalTitle: { fontSize: 17, fontWeight: '700' },
  modalBody: { padding: 20, gap: 14, paddingBottom: 40 },
  modalEquip: { fontSize: 18, fontWeight: '800' },
  detailRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1 },
  detailLabel: { fontSize: 13 },
  detailValue: { fontSize: 13, fontWeight: '600', maxWidth: '55%', textAlign: 'right' },
  notesBox: { borderRadius: 12, padding: 14, gap: 4 },
  notesLabel: { fontSize: 11, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 0.5 },
  notesText: { fontSize: 14, lineHeight: 20 },
  fieldGroup: { gap: 6 },
  label: { fontSize: 13, fontWeight: '600' },
  inputWrapper: { borderWidth: 1.5, borderRadius: 12, padding: 12 },
  input: { fontSize: 14, minHeight: 60 },
  actionsCol: { gap: 10, marginTop: 4 },
  actionBtnLarge: { borderRadius: 12, paddingVertical: 14, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8 },
  actionBtnText: { color: '#FFF', fontSize: 15, fontWeight: '700' },
  searchRow: { paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1 },
  searchWrapper: {
    flexDirection: 'row', alignItems: 'center', gap: 8,
    borderWidth: 1.5, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 9,
  },
  searchInput: { flex: 1, fontSize: 14, padding: 0 },
});

export default RentalRequestsStyle;
