import { StyleSheet } from 'react-native';

const AdminDashboardStyle = StyleSheet.create({
  safe: { flex: 1 },
  header: { paddingTop: 20, paddingBottom: 24, paddingHorizontal: 20, gap: 16 },
  headerTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  greeting: { fontSize: 13, color: 'rgba(255,255,255,0.6)' },
  userName: { fontSize: 22, fontWeight: '800', color: '#FFFFFF' },
  adminBadge: {
    width: 44, height: 44, borderRadius: 22,
    alignItems: 'center', justifyContent: 'center',
  },
  alertBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(249,115,22,0.3)',
    borderRadius: 12,
    padding: 12,
  },
  alertText: { flex: 1, color: '#FFFFFF', fontSize: 13, fontWeight: '600' },
  statsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 12,
    gap: 10,
  },
  statCard: {
    width: '30%',
    flexGrow: 1,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    gap: 6,
    borderWidth: 1,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  statIcon: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  statValue: { fontSize: 16, fontWeight: '800', textAlign: 'center' },
  statLabel: { fontSize: 11, textAlign: 'center' },
  section: { padding: 16, paddingBottom: 0 },
  sectionTitle: { fontSize: 17, fontWeight: '700', marginBottom: 12 },
  actionsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  actionCard: {
    width: '47%',
    flexGrow: 1,
    borderRadius: 14,
    padding: 16,
    alignItems: 'center',
    gap: 8,
    borderWidth: 1,
  },
  actionLabel: { fontSize: 13, fontWeight: '600', textAlign: 'center' },
  rentalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 14,
    borderRadius: 12,
    marginBottom: 8,
    borderWidth: 1,
  },
  rentalInfo: { flex: 1, gap: 4 },
  rentalEquip: { fontSize: 14, fontWeight: '600' },
  rentalCustomer: { fontSize: 12 },
  rentalRight: { alignItems: 'flex-end', gap: 6 },
  rentalCost: { fontSize: 13, fontWeight: '700' },
});

export default AdminDashboardStyle;
